name: Build and Publish React Native App to Expo

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Expo CLI and EAS CLI
        run: |
          npm install -g expo-cli @expo/eas-cli

      - name: Install dependencies
        run: npm install

      - name: Build and publish app to Expo
        run: |
          eas login --username ${{ secrets.EXPO_USERNAME }} --password ${{ secrets.EXPO_PASSWORD }}
          eas publish --release-channel ${{ github.sha }}
