name: Build and Publish React Native App

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Authenticate to EAS
      uses: expo/expo-github-action@v5
      with:
        expo-version: '4.x'
        expo-username: ${{ secrets.EAS_USERNAME }}
        expo-password: ${{ secrets.EAS_PASSWORD }}

    - name: Publish the app using EAS
      run: eas publish
      env:
        EAS_TARGET: production
